"""Shared suggestion data for TOAN AAS image/video planning flows."""

CREATIVE_SUGGESTIONS = {
    "vi": {
        "video_topic_suggestions": [
            "Nước hoa nam cao cấp cho người đi làm",
            "App AI automation cho chủ shop nhỏ",
            "Khóa học affiliate cho người mới",
            "Quán cà phê mới mở gần trường đại học",
            "Balo chống nước cho dân văn phòng",
            "Máy xay sinh tố mini cho người bận rộn",
            "Dịch vụ thiết kế landing page cho shop online",
            "Bộ skincare routine buổi sáng",
            "Đèn bàn thông minh cho creator",
            "Homestay ven biển cho chuyến đi cuối tuần",
            "Tool quản lý khách hàng cho freelancer",
            "Khóa học tiếng Anh cho người đi làm",
            "Tai nghe chống ồn giá tốt",
            "Dịch vụ chỉnh ảnh sản phẩm",
            "Nhà hàng rooftop mới khai trương",
            "Template quản lý tài chính cá nhân",
            "Bình giữ nhiệt phong cách tối giản",
            "Gói tư vấn xây kênh TikTok",
            "Căn hộ mẫu dành cho gia đình trẻ",
            "Hộp meal prep healthy cho bố mẹ bận rộn",
        ],
        "video_style_suggestions": [
            "Quảng cáo sản phẩm sạch với hero reveal",
            "Cinematic cảm xúc với nhịp dựng chậm",
            "TikTok/Reels nhanh với hook mạnh",
            "Luxury đen trắng với ánh sáng viền",
            "UGC đời thường, gần gũi và đáng tin",
            "Before/after rõ kết quả",
            "Công nghệ tương lai, ánh sáng xanh ngọc",
            "Tutorial ngắn với cutaway chi tiết",
            "Kể chuyện thương hiệu theo hành trình nhân vật",
        ],
        "video_motion_suggestions": [
            "Slow push-in vào chủ thể chính",
            "Orbit nhẹ quanh sản phẩm",
            "Handheld tự nhiên theo bước chân",
            "Macro detail rồi pull-back reveal",
            "Match cut before/after cùng bố cục",
            "Parallax 2.5D tạo chiều sâu",
            "Dolly-in mượt theo nhịp voice",
            "Snap zoom nhanh kiểu TikTok",
            "Pan ngang chậm qua bối cảnh",
        ],
        "video_transition_suggestions": [
            "Fade mềm giữa các cảnh",
            "Match cut theo hình dạng/chuyển động",
            "Slide ngang nhẹ theo nhịp",
            "Whip pan ngắn cho video nhanh",
            "Dissolve chậm cho cảm xúc cinematic",
            "Zoom transition rất nhẹ",
            "Cut theo beat nhạc",
            "Before/after split transition",
            "Chuyển cảnh bằng vật thể che camera",
        ],
        "video_music_voice_suggestions": [
            "Piano cinematic nhẹ, voice gần gũi",
            "Electronic future, voice tự tin",
            "Upbeat TikTok, câu đọc ngắn và nhanh",
            "Ambient luxury, voice trầm sang",
            "UGC acoustic, voice đời thường",
            "Corporate nhẹ, voice thuyết minh rõ",
            "Emotional strings, voice kể chuyện",
            "Lo-fi sạch, voice hướng dẫn chậm",
            "Không nhạc, ưu tiên voice và SFX tinh tế",
        ],
        "video_reference_analysis_templates": [
            "Phân tích hook → vấn đề → giải pháp → CTA",
            "Phân tích nhịp TikTok/Reels và điểm giữ người xem",
            "Phân tích cấu trúc cinematic ba hồi",
            "Phân tích tutorial theo từng bước dễ làm theo",
            "Phân tích before/after và match cut",
            "Phân tích UGC review và bằng chứng sử dụng",
            "Phân tích product reveal và góc quay chi tiết",
            "Phân tích brand story và cảm xúc",
            "Phân tích video affiliate theo hook/demo/CTA",
        ],
        "marketing_campaign_suggestions": [
            "Ra mắt sản phẩm mới trong 7 ngày",
            "Chiến dịch TikTok Shop cho người mới",
            "Chuỗi nội dung giáo dục trước khi bán",
            "Chiến dịch before/after tăng niềm tin",
            "UGC review kết hợp ưu đãi mềm",
            "Kế hoạch kéo khách về website",
            "Chuỗi video giải đáp câu hỏi thường gặp",
            "Chiến dịch khai trương địa điểm mới",
            "Kế hoạch nuôi lead bằng nội dung ngắn",
        ],
        "dubbing_voice_suggestions": [
            "Nam tự nhiên, tốc độ vừa",
            "Nữ tự nhiên, rõ chữ",
            "Giọng quảng cáo tự tin",
            "Giọng thuyết minh chuyên nghiệp",
            "Giữ cảm xúc gốc, nhịp nói tự nhiên",
            "Giọng trẻ trung cho TikTok/Reels",
            "Giọng trầm cho nội dung luxury",
            "Giọng nhẹ cho giáo dục/hướng dẫn",
            "Voice trung tính cho video doanh nghiệp",
        ],
        "caption_cta_suggestions": [
            "Xem chi tiết và chọn phiên bản phù hợp với bạn.",
            "Lưu video để thử lại khi cần.",
            "Nhắn TOAN AAS nếu bạn muốn một phiên bản riêng.",
            "Bình luận từ khóa để nhận checklist.",
            "Xem link trong mô tả nếu sản phẩm phù hợp nhu cầu.",
            "Theo dõi để xem phần hướng dẫn tiếp theo.",
            "Thử ngay hôm nay và so sánh kết quả.",
            "Chia sẻ cho người đang gặp vấn đề tương tự.",
            "Đặt lịch tư vấn nếu bạn cần lộ trình cụ thể.",
        ],
        "image_topic_suggestions": [
            "Logo thương hiệu tối giản",
            "Banner mạng xã hội",
            "Ảnh sản phẩm studio",
            "Ảnh quảng cáo cinematic",
            "Key visual công nghệ AI",
            "Ảnh lifestyle dùng sản phẩm",
            "Poster khuyến mãi",
            "Ảnh nhân vật đại diện thương hiệu",
            "Ảnh before/after",
            "Ảnh thumbnail YouTube",
            "Ảnh bài đăng Facebook",
            "Ảnh TikTok/Reels cover",
            "Ảnh landing page hero",
            "Ảnh concept luxury",
            "Ảnh food/drink quảng cáo",
            "Ảnh bất động sản mẫu",
            "Ảnh khóa học online",
            "Ảnh app/software mockup",
            "Ảnh quà tặng/sự kiện",
            "Ảnh tuyển dụng/đội nhóm",
        ],
    },
    "en": {
        "video_topic_suggestions": [
            "Premium men's fragrance for professionals",
            "AI automation app for small shops",
            "Affiliate course for beginners",
            "New coffee shop near a university",
            "Waterproof backpack for office workers",
            "Mini blender for busy people",
            "Landing-page service for online shops",
            "Morning skincare routine",
            "Smart desk lamp for creators",
            "Beach homestay for weekend trips",
            "Client management tool for freelancers",
            "English course for professionals",
            "Affordable noise-cancelling headphones",
            "Product photo editing service",
            "New rooftop restaurant launch",
            "Personal finance template",
            "Minimal insulated bottle",
            "TikTok channel consulting package",
            "Model apartment for young families",
            "Healthy meal-prep box for busy parents",
        ],
        "video_style_suggestions": [
            "Clean product ad with a hero reveal",
            "Emotional cinematic pacing",
            "Fast TikTok/Reels with a strong hook",
            "Black-and-white luxury lighting",
            "Natural and trustworthy UGC",
            "Clear before-and-after result",
            "Future technology with turquoise light",
            "Short tutorial with detail cutaways",
            "Character-led brand story",
        ],
        "video_motion_suggestions": [
            "Slow push-in on the main subject",
            "Gentle orbit around the product",
            "Natural handheld follow movement",
            "Macro detail then pull-back reveal",
            "Matched before-and-after cut",
            "Subtle 2.5D parallax",
            "Smooth dolly-in paced to narration",
            "Fast TikTok snap zoom",
            "Slow horizontal pan across the scene",
        ],
        "video_transition_suggestions": [
            "Soft fade between scenes",
            "Shape or motion match cut",
            "Gentle horizontal slide",
            "Short whip-pan for fast video",
            "Slow dissolve for cinematic emotion",
            "Subtle zoom transition",
            "Music-beat cut",
            "Before-and-after split transition",
            "Foreground wipe transition",
        ],
        "video_music_voice_suggestions": [
            "Soft cinematic piano with a friendly voice",
            "Future electronic bed with confident narration",
            "Upbeat TikTok music with short fast lines",
            "Luxury ambient bed with a deep voice",
            "Acoustic UGC bed with everyday narration",
            "Light corporate music with clear narration",
            "Emotional strings with story voiceover",
            "Clean lo-fi with slow tutorial narration",
            "No music, prioritize voice and subtle SFX",
        ],
        "video_reference_analysis_templates": [
            "Hook → problem → solution → CTA",
            "TikTok/Reels pacing and retention beats",
            "Three-act cinematic structure",
            "Step-by-step tutorial structure",
            "Before/after and match-cut structure",
            "UGC review and usage proof",
            "Product reveal and detail shots",
            "Brand story and emotional arc",
            "Affiliate hook/demo/CTA structure",
        ],
        "marketing_campaign_suggestions": [
            "Seven-day product launch",
            "TikTok Shop starter campaign",
            "Educational content before selling",
            "Before/after trust campaign",
            "UGC reviews with a soft offer",
            "Website traffic campaign",
            "FAQ short-video series",
            "New venue opening campaign",
            "Lead-nurturing short-content plan",
        ],
        "dubbing_voice_suggestions": [
            "Natural male, medium pace",
            "Natural female, clear diction",
            "Confident advertising voice",
            "Professional documentary narration",
            "Preserve the original emotion",
            "Youthful short-form voice",
            "Deep luxury voice",
            "Gentle educational voice",
            "Neutral corporate voice",
        ],
        "caption_cta_suggestions": [
            "See the details and choose the version that fits you.",
            "Save this video for later.",
            "Message TOAN AAS for a custom version.",
            "Comment the keyword to receive the checklist.",
            "See the description if the product fits your needs.",
            "Follow for the next tutorial.",
            "Try it today and compare the result.",
            "Share this with someone facing the same problem.",
            "Book a consultation for a tailored roadmap.",
        ],
        "image_topic_suggestions": [
            "Minimal brand logo",
            "Social media banner",
            "Studio product image",
            "Cinematic ad image",
            "AI technology key visual",
            "Lifestyle product-use image",
            "Promotion poster",
            "Brand mascot or spokesperson image",
            "Before-and-after image",
            "YouTube thumbnail",
            "Facebook post image",
            "TikTok/Reels cover",
            "Landing-page hero image",
            "Luxury concept image",
            "Food/drink advertising image",
            "Real-estate sample image",
            "Online course image",
            "App/software mockup",
            "Gift/event image",
            "Team/recruitment image",
        ],
    },
}


def creative_suggestion_bank(key: str, lang: str = "vi") -> list[str]:
    language = "vi" if str(lang or "").lower().startswith("vi") else "en"
    bank = CREATIVE_SUGGESTIONS.get(language, CREATIVE_SUGGESTIONS["vi"])
    return list(bank.get(str(key or ""), []))


def rotating_suggestions(items: list[str], offset: int = 0, limit: int = 3) -> list[str]:
    clean = [str(item or "").strip() for item in items if str(item or "").strip()]
    if not clean:
        return []
    start = int(offset or 0) % len(clean)
    return [clean[(start + index) % len(clean)] for index in range(min(limit, len(clean)))]
